gateways:
    redshift_gateway:
        connection:
            type: redshift
            user: {{ env_var('REDSHIFT_USER') }}
            password: {{ env_var('REDSHIFT_PASSWORD') }}
            database: dev
            host: {{ env_var('REDSHIFT_HOST') }}
            port: 5439
            concurrent_tasks: 1

        state_connection:
            type: duckdb
            database: redshift_state.db

default_gateway: redshift_gateway

model_defaults:
    dialect: redshift

# enables synchronized deployments to prod when a PR is merged
cicd_bot:
    type: github
    merge_method: squash
    enable_deploy_command: true
    auto_categorize_changes:
      external: full
      python: full
      sql: full
      seed: full

plan:
  enable_preview: true

# list of users that are allowed to approve PRs for synchronized deployments
users:
- username: sung_sqlmesh_demo
  github_username: sungchun12
  roles:
    - required_approver
- username: afzal_sqlmesh_demo
  github_username: afzaljasani
  roles:
    - required_approver