gateways:
  tobiko_cloud: # this will use the config in tcloud.yaml for state_connection
    scheduler: # TODO: add the connection info below into the Tobiko Cloud Connections Page with the service account json in plain text for this scheduler
      type: cloud
      default_catalog: DEMO_DB # prod
    connection: # This connection is used for automatic unit test generation and external model creation
      type: snowflake
      account: idapznw-wq29399
      user: DEMO_USER
      password: {{ env_var('SNOWFLAKE_PASSWORD') }} # export SNOWFLAKE_PASSWORD=<your password>
      database: DEMO_DB
      warehouse: COMPUTE_WH

default_gateway: tobiko_cloud

model_defaults:
  dialect: snowflake
  start: 2024-12-01

linter:
  enabled: true
  # error if ["ambiguousorinvalidcolumn", "invalidselectstarexpansion"] rules violated
  rules: ["ambiguousorinvalidcolumn", "invalidselectstarexpansion"]
  # warn_rules: ["noselectstar"]
  # ignored_rules: ["noselectstar"]

# enables synchronized deployments to prod when a PR is merged
cicd_bot:
  type: github
  merge_method: squash
  enable_deploy_command: true
  skip_pr_backfill: false
  auto_categorize_changes:
    external: full
    python: full
    sql: full
    seed: full

plan:
  enable_preview: true

