name: Daily ELT Job
run-name: 🧃 Daily ELT Job 🧃

on:
  pull_request:
    types:
    - synchronize
    - opened
  # Required if using comments to issue commands to the bot
  # issue_comment:
  #   types:
  #   - created
  # Required if using required approvers to automate deployments
  pull_request_review:
    types:
    - edited
    - submitted
    - dismissed

# The latest commit is the one that will be used to create the PR environment and deploy to production
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  sqlmesh:
    name: SQLMesh Actions
    runs-on: ubuntu-latest
    permissions:
      # Required to access code in PR
      contents: write
      # Required to post comments
      issues: write
      # Required to update check runs
      checks: write
      # Required to merge
      pull-requests: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.pull_request && github.event.issue.number || github.event.pull_request.number  }}/merge

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_SQLMESH_CREDENTIALS }}'

      - name: Install SQLMesh Enterprise + Dependencies
        run: |
          pip install poetry keyring keyrings-google-artifactregistry-auth
          pip install ruff==0.4.8 mypy==1.10.0 pytest==8.1.1
          pip install "sqlmesh-enterprise[bigquery,web,services,github]==0.27.0" --extra-index-url ${{ secrets.SQLMESH_ENTERPRISE_TOKEN }}
        shell: bash

      - name: Append raw events to tcloud_raw_data.raw_events
        run: |
          python demo_scripts/main.py append-rawdata --end-date 2024-07-31
        env:
          GOOGLE_SQLMESH_CREDENTIALS: ${{ secrets.GOOGLE_SQLMESH_CREDENTIALS }}

      - name: Run CI/CD Bot
        run: |
          sqlmesh run
        env: # TODO: update your GitHub secrets to include TOBIKO_CLOUD_TOKEN, GOOGLE_SQLMESH_CREDENTIALS
          TOBIKO_CLOUD_TOKEN: '${{ secrets.TOBIKO_CLOUD_TOKEN }}'
          GOOGLE_SQLMESH_CREDENTIALS: ${{ secrets.GOOGLE_SQLMESH_CREDENTIALS }}